### ISSUE TITLE
Error: No connection options were found in any of configurations file.

### ISSUE THREAD

**Issue by iljab** [w3tecch/typeorm-seeding#1]
I have a ormconfig.json in the root of the project, but i get the following error, when i try to run a seed:

Error: No connection options were found in any of configurations file.

The seed is executed in the root too.

**Comment by armanfatahi** [comment]
Just a wild shot: If you are running this on a docker container, make sure to copy the config file to the container!

**Comment by hirsch88** [comment]
Hi @iljab I use the seeding with the ormconfig.js file, which is in the root of my project.
I added a new cli to the project. 
Try the cli and use the config option to tell the cli where the config file is.

**Comment by vuk-nikolic** [comment]
I know it's an old issue, but to confirm that adding --config helped me.
Thanks!
