### ISSUE TITLE
Typeorm should be a peerDependency

### ISSUE THREAD

**Issue by bpatram** [w3tecch/typeorm-seeding#11]
Hi guys, I'm running into an issue in my project where typeorm-seeding is installing its own typeorm library on top of the one I install for my project. This causes some issues, especially surrounding typing in Typescript projects when implementing Seeders.

Typeorm should be listed as a peer-dependency in this library to avoid duplicate Typeorm libs from being installed for end users (like me).

In my specific case this is the error I hit:

```typescript
import { Factory, Seeder } from 'typeorm-seeding';
import { Connection } from 'typeorm';

export class CreateStreams implements Seeder {
  public async run(factory: Factory, connection: Connection) {
  }
}
```
TS error displayed:
```
Property 'run' in type 'CreateStreams' is not assignable to the same property in base type 'Seeder'.
  Type '(factory: import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm-seeding/dist/types").Factory, connection: import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm/connection/Connection").Connection) => Promise<...>' is not assignable to type '(factory: import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm-seeding/dist/types").Factory, connection: import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm-seeding/node_modules/typeorm/connection/Connection").Connection) => Promise<...>'.
    Types of parameters 'connection' and 'connection' are incompatible.
      Type 'import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm-seeding/node_modules/typeorm/connection/Connection").Connection' is not assignable to type 'import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm/connection/Connection").Connection'.
        Types of property 'options' are incompatible.
          Type 'import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm-seeding/node_modules/typeorm/connection/ConnectionOptions").ConnectionOptions' is not assignable to type 'import("/Volumes/work_projects/slewsystems_pi67_webserver/node_modules/typeorm/connection/ConnectionOptions").ConnectionOptions'.
```

What you'll notice is the `Connection` type I define is located in:
`node_modules/typeorm/connection/Connection`
but the typoeorm-seeding types is looking in:
`node_modules/typeorm-seeding/node_modules/typeorm/connection/Connection`
because I have two typeorm libraries installed.

As a workaround I've been leveraging Yarn's resolution capabilities and its autodedup like this:

```json
{
  "dependencies": {
    "typeorm": "^0.2.17",
  },
  "devDependencies": {
    "typeorm-seeding": "^1.0.0-rc.2"
  },
  "resolutions": {
    "typeorm-seeding/typeorm": "^0.2.17"
  }
}
```

**Comment by jpdesigndev** [comment]
I think `typeorm` should be listed as a peerDependency as well. It would be nice if this happened before 1.0.0 was released.

**Comment by chasen-bettinger** [comment]
Thanks @bpatram . This worked for me :)

**Comment by hirsch88** [comment]
Done with https://github.com/w3tecch/typeorm-seeding/pull/22

**Comment by marcosfreitas** [comment]
Guys, why is the peerDependency an old version of the TypeORM?

I'm getting this warning: `warning " > typeorm-seeding@1.6.1" has incorrect peer dependency "typeorm@^0.2.24".`

TypeORM version used: `^0.3.7`
TypeORM Seeding version used: `^1.6.1`
