### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by metalcamp** [w3tecch/typeorm-seeding#116]
Is this package maintained at all or can we consider it deprecated? 
If you're looking for maintainers please say so.

**Comment by hirsch88** [comment]
Hi @metalcamp , would be really glad if you could help to maintain this project

**Comment by jorgebodega** [comment]
I think this package is still unmaintained. Please, I use it and could be great to fix some errors.

I could help too if you need it.

**Comment by RaphaelWoude** [comment]
I would love to help out as well

**Comment by hirsch88** [comment]
Hi @jorgebodega & @RaphaelWoude 

I added you to this repo. You should now be able to help me maintain it.

Thank you

**Comment by metalcamp** [comment]
Wow, thank you! 
I'm on a bit tight schedule lately but I'll try to work something out.
