### ISSUE TITLE
How to work with transactional rollback?

### ISSUE THREAD

**Issue by gaggle** [w3tecch/typeorm-seeding#118]
Hi, I can't get this package working with transactional rollback in tests and I'm not sure if it's intentional, or a bug, or something I can work around...

I have a connection wrapped in a transactional rollback, and I expect typeorm-seeding to create data that ends up rolled back at the end of the test. But instead the factory created data actually gets persisted.

I'm using https://github.com/entrostat/typeorm-test-transactions for the rollback but I don't think that's very important, but here's the the minimal repro sample I've come up:
```
import { createConnection } from 'typeorm';
import { factory, useSeeding } from 'typeorm-seeding';
import { initialiseTestTransactions, runInTransaction } from 'typeorm-test-transactions';
import { Interval } from '../../shared/constants';
import { UserProfile } from '../entity/user-profile.entity';

// 1. The intent with this is that from now on transactions can be run inside `runInTransaction` 
// and any changes will be rolled back automatically
initialiseTestTransactions();

describe('foo', () => {
  beforeAll(async () => {
    await createConnection();
    await useSeeding();
  });

  it('typeorm-seeding', runInTransaction(async () => {
    await factory(UserProfile)().create({ foo: "bar });
  }));
});
```
(Here `UserProfile` is just some TypeORM entity, it's as simple as the `User` and `Pet` entities from the README.md)

Unfortunately the outcome of running this test is a **persisted row in the database**. Somehow typeorm-seeding is bypassing the transaction?

---

To prove I'm not too confused I've also run the test without invoking typeorm-seeding:
```
  it('raw', runInTransaction(async () => {
      const e = await UserProfile.create({
        income: 123,
        incomeInterval: Interval.Month,
      });
      await e.save();
    })
  );
```
And this test does not persist any rows (and if I remove the `runInTransaction` then it does persist, as expected).

Does anyone recognize the problem here? Am I just missing some obvious way of passing in a connection? I've gone over the documentation several times but nothing really sticks out as a solution. Any insights appreciated!

(FWIW this is running against a Postgres database, I can't do in-memory tests as suggested in the readne because of the subtle ways sqlite and Postgres are not compatible)

**Comment by gaggle** [comment]
And hey thanks for making this package available, I think the factory semantics feel very natural to write and use. I obviously hope I can get beyond the problem I've struggled with today, but regardless thank you for making the library available :)

**Comment by EPecherkin** [comment]
I'm having the same issue. Given the fact that running test in transactions is crucial - the inability to do that makes this library useless in my projects :(
@gaggle did you find a workaround?

**Comment by gaggle** [comment]
Of a sorts, yes, insofar I rolled our own. No special magic, just some plain NestJS classes to create entities, and because its all vanilla NestJS they behave like everything else and are easy to pull into tests etc.

**Comment by jorgebodega** [comment]
Humm, could be interesting to implement this, don't know how to start but is definitely something interesting.

**Comment by jorgebodega** [comment]
I will move the discussion to the maintained repo.
