### ISSUE TITLE
Use with .env

### ISSUE THREAD

**Issue by dothem1337** [w3tecch/typeorm-seeding#12]
Hey

Currently it's static, using the ormconfig.js. But I use .env as config. Are there any chance to get this run with .env?

Thank you

**Comment by bpatram** [comment]
Hi @dothem1337,

Are you able to reference your env variables using [`process.env.*`](https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_process_env)?

If you are using the [dotenv package](https://github.com/motdotla/dotenv) I think you would invoke the CLI like this:

```bash
node -r dotenv/config node_modules/typeorm-seeding/dist/cli.js seed --config ormconfig.js

# or if you're using TypeScript:
node -r dotenv/config -r ts-node/register node_modules/typeorm-seeding/dist/cli.js seed --config ormconfig.js
```

Example configuration file:
```js
// ormconfig.js

module.exports = {
   host: process.env.DATABASE_HOST,
   username: process.env.DATABASE_USER,
   password: process.env.DATABASE_PASSWORD,
   // ...
};
```

**Comment by bpatram** [comment]
Looking at this again, I'm guessing you are referencing this functionality provided by TypeORM: https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-environment-variables _(sorry, I don't use this functionality, but I thought this was an interesting issue 😉)_

To the maintainers of this library:
I think to get this support you'll want to use the `ConnectionOptionsReader` class TypeORM provides. Then you'll call the `load()` function on it, which will look for the env files and load it in. 

https://github.com/typeorm/typeorm/blob/117185b5e5d7a4672af6ba1f1341de98fa8d1fef/src/connection/ConnectionOptionsReader.ts#L95-L101

**Comment by sgarner** [comment]
> To the maintainers of this library:
> I think to get this support you'll want to use the `ConnectionOptionsReader` class TypeORM provides. Then you'll call the `load()` function on it, which will look for the env files and load it in.
> 

Using TypeORM's provided `ConnectionOptionsReader` would also enable support for configuration in YAML format which is currently broken. 🙁

**Comment by billbarni** [comment]
I updated this package on the 'express-typescript-boilerplate' and several classes in the 'seed.ts' can't be used anymore.

**Comment by hirsch88** [comment]
hi @dothem1337 
I have finally included this feature. try out the new version 1.4.0
