### ISSUE TITLE
Add support to call seeders

### ISSUE THREAD

**Issue by RaphaelWoude** [w3tecch/typeorm-seeding#122]
I want to insert another table after one has been executed for a relation, but that is not possible at the moment as the seeders are just being ran from the folder in alphabetic order.

Laravel has this feature and it would be nice to have.
https://laravel.com/docs/8.x/seeding

**Comment by AmrAbdalrahman** [comment]
the workaround you can use [this solution](https://github.com/w3tecch/typeorm-seeding/issues/91#issuecomment-685904757)
