### ISSUE TITLE
Running single seed

### ISSUE THREAD

**Issue by tmtung144** [w3tecch/typeorm-seeding#129]
I need to run each seed operation individually, in the terminal when I run seed: run I see an option:
`--seed, -s        Specific seed class to run.`
but when i run the command:
`npm run typeorm-seeding seed -s CreateUsers`
with my seed file **1-create-users.seed.ts** like this:
```
...
export default class CreateUsers implements Seeder {
...
}
```
It keeps announcing `Unknown argument: CreateUsers`
It works well when it's just running `npm run typeorm-seeding seed`
Looking forward to receiving any useful advice.

**Comment by micalevisk** [comment]
What about running with `--seed`?

**Comment by AmrAbdalrahman** [comment]
try run `ts-node ./node_modules/typeorm-seeding/dist/cli.js seed -s CreateUsers`
works well

**Comment by micalevisk** [comment]
@tmtung144 Since you are using `npm run ...` the `-s` flag will be passed to `npm run` command, not to `typeorm-seeding seed`

Use `npm run typeorm-seeding -- seed -s CreateUsers` or with Yarn `yarn typeorm-seeding seed -s CreateUser`

**Comment by nguyentuan7277** [comment]
> @tmtung144 Since you are using `npm run ...` the `-s` flag will be passed to `npm run` command, not to `typeorm-seeding seed`
> 
> Use `npm run typeorm-seeding -- seed -s CreateUsers` or with Yarn `yarn typeorm-seeding seed -s CreateUser`

Not work for me.

**Comment by metalcamp** [comment]
Closing, since it seems to be resolved. If you have any further issues regarding this topic please feel free to reopen.
