### ISSUE TITLE
In factory: TypeError: Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by volovodenko** [w3tecch/typeorm-seeding#131]
faker.random.number({ min: 0, max: 10, precision: 0.001 }) - this work 
faker.datatype.number({ min: 0, max: 10, precision: 0.001 }) - this cause TypeError: Cannot read property 'number' of undefined

**Comment by thakkaryash94** [comment]
That's because this package internally using an old faker version. https://github.com/w3tecch/typeorm-seeding/blob/master/package.json#L59

**Comment by RaphaelWoude** [comment]
https://github.com/w3tecch/typeorm-seeding/releases/tag/v1.6.2

**Comment by mfasanya** [comment]
Can we get the latest version pushed to npm?

**Comment by RaphaelWoude** [comment]
@hirsch88
