### ISSUE TITLE
Can you please bump faker's version upto v5.5.3 please

### ISSUE THREAD

**Issue by AaronNGray** [w3tecch/typeorm-seeding#141]
Can you please bump faker's version upto ^5.5.3 please as the images and avatar URL's have been modified in the latest version to be valid image URL's again.
https://github.com/Marak/faker.js/issues/1206

**Comment by dontwan** [comment]
I need this too! Because some random options are deprecated, and I need `faker.random.alpha` which is not available in the current version.

**Comment by NarHakobyan** [comment]
Hi guys, I've forked and removed faker from deps, you can use this repo as deps

https://github.com/NarHakobyan/typeorm-seed

**Comment by RaphaelWoude** [comment]
Bumped to version v5.5.3 https://github.com/w3tecch/typeorm-seeding/commit/de1a27dc6c1c51022a315e0e0b952c6d68f676eb
