### ISSUE TITLE
import { Seed } Error

### ISSUE THREAD

**Issue by koheiiwamura** [w3tecch/typeorm-seeding#15]

**Comment by koheiiwamura** [comment]
Hi.

I installed typeorm-seeding (version "1.0.0-rc.3").

and import modules for seeding data in database.
But this error was happened.

<img width="1182" alt="スクリーンショット 2019-07-03 15 54 29" src="https://user-images.githubusercontent.com/20556861/60569768-117ec580-9dab-11e9-8443-b4a826240134.png">


```
Module '"../../../../../../../Users/apple/projects/famm-snap/famm-snap-backend/node_modules/typeorm-seeding/dist/typeorm-seeding"' has no exported member 'Seed'
```

I can import `Factory`, but I can't import `Seed`

**Comment by iquabius** [comment]
The API has changed in [this commit](https://github.com/w3tecch/typeorm-seeding/commit/84df81147db14f96311b593bc2575b15f472088d). The interface is now called `Seeder`.

**Comment by mreschke** [comment]
Because of this your Docs and example project https://github.com/w3tecch/express-typescript-boilerplate are broken and invalid

**Comment by endurance** [comment]
That's a pretty big deal, this change makes the library look like it isn't ready for production use.
