### ISSUE TITLE
Can't install the latest version 1.6.2

### ISSUE THREAD

**Issue by Jedliu** [w3tecch/typeorm-seeding#153]
Hi,

I can't install the latest version 1.6.2. and the version on NPM is still 1.6.1.
[https://www.npmjs.com/package/typeorm-seeding](https://www.npmjs.com/package/typeorm-seeding)

I tried
```
npm install typeorm-seeding@1.6.2
```
but it doesn't work.

Thank you,

**Comment by RaphaelWoude** [comment]
I would love to send out a new version but unfortunately I do not have the permission to. 
We will have to wait for @hirsch88 to push the newest version.

**Comment by Jedliu** [comment]
Okay, thank you for your reply. We'll wait for @hirsch88 .
