### ISSUE TITLE
Bump package versions

### ISSUE THREAD

**Issue by jorgebodega** [w3tecch/typeorm-seeding#161]
Currently some packages are outdated. We could update manually or try to update with some kind of bot, like renovate or dependabot.

This is the list

![imagen](https://user-images.githubusercontent.com/23708828/137013569-024ed618-4b94-41c1-b2b2-928bfea0573c.png)

- [ ] @semantic-release/git    
- [x] #171
- [x] #172
- [x] #167
- [x] #173
- [x] #168
- [x] #166  
- [ ] semantic-release    
- [x] #177
- [x] #193
- [x] #164
- [x] #175
- [x] #179

**Comment by jorgebodega** [comment]
I'm pretty sure we should discuss about what node version we support. This is pretty important, since Node 16 is going to be LTS this month, and because target are pretty diferent.

[Node 12 tsconfig recommended](https://github.com/tsconfig/bases/blob/main/bases/node12.json)
[Node 14 tsconfig recommended](https://github.com/tsconfig/bases/blob/main/bases/node14.json)
[Node 16 tsconfig recommended](https://github.com/tsconfig/bases/blob/main/bases/node16.json)

@hirsch88

**Comment by Dmitriyx** [comment]
Can we also bump Faker package please.

typeorm-seeding@^1.6.1:
    faker "4.1.0" ->     **faker "5.5.3"**

**Comment by Dmitriyx** [comment]
we also need to upgrade faker dependency

 `yarn check v1.22.10
error "typeorm-seeding#faker" is wrong version: expected "4.1.0", got "5.5.3"
error "nps#spawn-command-with-kill#ps-tree#event-stream" is wrong version: expected "=3.3.4", got "4.0.1"
error Found 2 errors.`

**Comment by jorgebodega** [comment]
`faker` is already upgraded on `v1.6.2` but is not deployed because we do not have permission to do it. Check #156

**Comment by micalevisk** [comment]
will `typeorm-seeding@1.6.2` be published soon? I want to use `faker` v5

```
$ npm info typeorm-seeding version
1.6.1
```

**Comment by jorgebodega** [comment]
New version cannot be released because of #153.

There is a workaround installing `faker` as a dependency and using it like

```typescript
import * as faker from 'faker' // Use this instead of the other one
import { define } from 'typeorm-seeding'
import { User } from '../entities'

define(User, () => { ... })
```

**Comment by micalevisk** [comment]
oh of course. I felt dumb. Thanks

**Comment by jorgebodega** [comment]
I know that is not the ideal workaround.

If NPM token is not created when the next version will be ready, I will deploy it myself.

**Comment by jorgebodega** [comment]
Closing this, no versions could be deployed
