### ISSUE TITLE
Adapt seeder to an abstract class

### ISSUE THREAD

**Issue by jorgebodega** [w3tecch/typeorm-seeding#185]
To fix #119 we need to find a way to avoid the problem of export multiple elements but not checking if those are seeder.

A possible approach is to define Seeders as an abstract class instead of an interface. That will allow us to use `instanceof` to infer what could be used as a seeder. Similarly to new [seeder](https://github.com/mikro-orm/mikro-orm/blob/master/packages/seeder/src/seeder.ts) of MikroORM.

Or we can discuss about allowing only default exports

**Comment by micalevisk** [comment]
**+1** to `class MySeeder extends Seeder { ... }` approach.

**Comment by jorgebodega** [comment]
Closed by #191
