### ISSUE TITLE
Enity metadata not found on running seed 

### ISSUE THREAD

**Issue by GhettoBurger996** [w3tecch/typeorm-seeding#192]
Hey all, 

I'm attempting to seed some test data but whenever I try running the function it returns 
`TypeORMError: Entity metadata for FacilityPrice#facility was not found.` the issue is the connection is working fin when I attempt to run any request (query builder). Moreover, I tried deleting the **FacilityPrice#facility** and it ends up returning another error for another reference somewhere, this process continues until I've deleted everything but the user table (the table I am attempting to seed) only then does it work. 

Below is the config file setup. Any assistance is much appreciated. 

**ormconfig.ts (typescript file)**
```
module.exports = {
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "---",
  password: "---",
  database: "---",
  migrationsRun: true,
  synchronize: false,
  logging: true,
  logger: "advanced-console",
  migrationsTableName: "migrations",
  migrations: ["migrations/*.ts"],
  cli: {
    migrationsDir: "migrations",
  },
  namingStrategy: new CustomNamingStrategy(),
  // seeds: [__dirname + "seeds/seeds/**/*{.ts,.js}"],
  // factories: [__dirname + "seeds/factories/**/*{.ts,.js}"],
  // entities: [__dirname + "apps/entities/**/*.entity{.ts,.js}"],

  seeds: ["seeds/seeds/**/*{.ts,.js}"],
  factories: ["seeds/factories/**/*{.ts,.js}"],
  entities: ["apps/entities/**/*.entity{.ts,.js}"],
};
```

**Comment by jorgebodega** [comment]
I had this error last week in other project and it was related on how typeorm handle extensions. Could you create some example repo to check this case?

**Comment by GhettoBurger996** [comment]
yeah sure while I create the sample repo. How did you deal with the issue on your end ?

**Comment by jorgebodega** [comment]
I couldn't. https://github.com/typeorm/typeorm/issues/5124

I needed to do a stepback and remove abstract classes. A real pain.

**Comment by GhettoBurger996** [comment]
alright, heres the repo https://github.com/GhettoBurger996/typeorrm-seed

**Comment by jorgebodega** [comment]
Ok, i will check this evening. I'm going to work again on this repo this week

**Comment by jorgebodega** [comment]
I found that the error in your example repo is just naming. [One of your entities](https://github.com/GhettoBurger996/typeorrm-seed/blob/4e8fd3ab9d32a343deefec5b64a45c8341c2fb5f/apps/entities/facility.entitiy.ts) does not complain required `regexp`, and typeorm could not find that as entity.

Pls check if that is your problem, make sure that every file is well defined.

P.D.: I will close this, it is more related to typeorm (like [this one](https://github.com/typeorm/typeorm/issues/420))
