### ISSUE TITLE
Swap out Faker for @faker-js/faker

### ISSUE THREAD

**Issue by kevin-mitchell** [w3tecch/typeorm-seeding#206]
After the "switcheroo" [that was pulled with Faker](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/), I imagine that it would be a good idea to switch Faker out for the accepted "official" fork of the original project.

See: https://fakerjs.dev/

My understanding is that the best way to approach this swap would be to wait for the 6.0.0 release of `@faker-js/faker` (as of this ticket being created the current package is `6.0.0-alpha.5`), then "just" swap out the libraries.

In a very quick test I found that it seems pretty simple to swap out "old faker" for "new faker", although I followed these steps https://github.com/faker-js/faker#typescript-support to make TypeScript happy (this may be unnecessary).

**Comment by jorgebodega** [comment]
Hi! I can make this change, but pls take a look on #201
