### ISSUE TITLE
Publish the latest version on NPM

### ISSUE THREAD

**Issue by cenk1cenk2** [w3tecch/typeorm-seeding#208]
Hey,

Thanks for this very useful library.

I would like to kindly ask you to please publish the latest version v1.6.2 on NPM since it includes fixes for the wrong shebang with #99.

**Comment by jorgebodega** [comment]
Please take a look on #201

**Comment by cenk1cenk2** [comment]
Hey sincerly sorry for missing that issue. Thanks for zhe information.

**Comment by jorgebodega** [comment]
No worries, if you are gonna use the other version, please open your issues on the corresponding repository
