### ISSUE TITLE
Update Faker to pull from the new @faker-js/faker repository.

### ISSUE THREAD

**Issue by codeninja** [w3tecch/typeorm-seeding#210]
The FakerJS repository was poisoned by the original developer and has been moved to a new fork. Faker should be changed to pull from : **https://github.com/faker-js/faker**

**Comment by harm-less** [comment]
I wanted the exact same thing. Luckily I figured someone had made a fork that included these changes and there was: https://github.com/zackarychapple/typeorm-seeding 

You just need to replace your `typeorm-seeding` package with this one.
We have a big repo and every test has past using this fork.

I can't thank you through a comment/issue at your repo @zackarychapple, so thanks for the effort, you helped me out!

**Comment by jorgebodega** [comment]
Hi! There is a pinned issue commenting the problem, no new versions could be deployed (#201) so is completely nosense to do that fix.

I forked the library after being working on it, but you can use the one you prefer.

**Comment by harm-less** [comment]
@jorgebodega I tried your fork but I only wanted an update of Faker as otherwise we needed to rewrite a lot of code due to the various API changes. Hence my suggestion in my previous comment.

Is there a published version from your lib with this requirement?

**Comment by jorgebodega** [comment]
I don't think there is a version with just that change, following version 2 there are many breaking changes.

But you can still install the package from your side and use it, instead of the one of the library
