### ISSUE TITLE
Faker got abandoned and NPM audit complains about it

### ISSUE THREAD

**Issue by iamannani** [w3tecch/typeorm-seeding#213]
With the abandoned project of faker, npm audit complains about colors.js that faker.js is using.

Link to the vulnerability : https://github.com/advisories/GHSA-5w9c-rv96-fr7g

there is a forked faker to replace the old one with the new faker : https://www.npmjs.com/package/@faker-js/faker

thanks

**Comment by jorgebodega** [comment]
Please, check the existent issues prior reporting another one.

[w3tecch/typeorm-seeding/issues (label:faker sort:updated-desc is:closed)](https://github.com/w3tecch/typeorm-seeding/issues?q=label%3Afaker+sort%3Aupdated-desc+is%3Aclosed)
