### ISSUE TITLE
Support TypeORM@v0.3.x

### ISSUE THREAD

**Issue by fossamagna** [w3tecch/typeorm-seeding#215]
Hi. Thank you for making a great package.
I would like to use typeorm-seeding with TypeORM@0.3.x.
I can not use latest version of typeorm-seeding with TypeORM@0.3.x., because of TypeORM@0.3.0 has many changes.

**Comment by Jedliu** [comment]
Same here. Thank you!

**Comment by jorgebodega** [comment]
Hi! I've working on my fork with typeorm 0.3.x, and there are many breaking changes.

Will take some time to do that change

https://github.com/jorgebodega/typeorm-seeding/pull/122
