### ISSUE TITLE
Replace `faker` with `@faker-js/faker`

### ISSUE THREAD

**Issue by ludgerey** [w3tecch/typeorm-seeding#229]
The original faker.js is abandoned for a few month now:

> FAQ - What happened to the original faker.js?
>
> This project was originally created and hosted at https://github.com/marak/Faker.js/ - however around 4th Jan, 2022 - the author decided to delete the repository (for unknown reasons).
>
> In the interest of the community, it has been decided that faker.js will continue to be maintained here and all help in its development will be appreciated.

... and the community moved to the repository https://github.com/faker-js/faker with its website at https://fakerjs.dev

We should migrate this project to use `@faker-js/faker`, otherwise users have to use the abandoned package, which is not nice.

**Comment by jorgebodega** [comment]
Please, check the existent issues prior reporting another one.

[w3tecch/typeorm-seeding/issues (label:faker sort:updated-desc is:closed)](https://github.com/w3tecch/typeorm-seeding/issues?q=label%3Afaker+sort%3Aupdated-desc+is%3Aclosed)

**Comment by ludgerey** [comment]
Sorry! I was looking for open issues only, as it appears not to be solved, right?
