### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by carzoglioemanuel** [w3tecch/typeorm-seeding#239]
Hi guys!
Am having a problem when i trying to install typeorm-seeding. Am using the last version of typeorm.
Am know that if i use "--legacy-peer-deps" will work, but we have not another solution for this? I think that is not the best way to fix it.

```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: typescript-template@0.0.1
npm ERR! Found: typeorm@0.3.11
npm ERR! node_modules/typeorm
npm ERR!   dev typeorm@"^0.3.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typeorm@"^0.2.24" from typeorm-seeding@1.6.1
npm ERR! node_modules/typeorm-seeding
npm ERR!   typeorm-seeding@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

**Comment by trsh** [comment]
Same here. Looks like project is abandoned.

**Comment by jorgebodega** [comment]
Please, check the pinned issue: #201

Your problem is not related to this package. `typescript-template` needs `typeorm@^0.3` but this package is pinned to `typeorm@^0.2`

**Comment by trsh** [comment]
@jorgebodega don't rush with the closing

```
pm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving:xxx@1.0.0
npm ERR! Found: typeorm@0.3.11
npm ERR! node_modules/typeorm
npm ERR!   typeorm@"^0.3.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typeorm@"^0.2.24" from typeorm-seeding@1.6.1
npm ERR! node_modules/typeorm-seeding
npm ERR!   typeorm-seeding@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\janis\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```

This repo is also on a old typeorm, one can see in pachages.json. Time to upgrade?

**Edit:**

Ouh, did not check the PIN

**Comment by jorgebodega** [comment]
Please, read the issue I attached previously.

**Comment by trsh** [comment]
@jorgebodega Hmm, so everything that is solved in https://github.com/jorgebodega/typeorm-seeding will be considered as closed issue here? It doesn't make much sense. People will continue to create same issues. Just peace of my mind. Thanks!

**Comment by jorgebodega** [comment]
You can try the other library, maybe it satisfies your requirements, but I will not maintain this library until the original authror comes back.

I don't have permissions to work like in the other repository.

**Comment by trsh** [comment]
I am just saying, maybe don't close issues here, just because they are solved in a another fork. And thank you for your work, I will check it out soon.

**Comment by jorgebodega** [comment]
The issue is closed because is not gonna be fixed. There is an issue fixed with explanations, so I will not discuss about this again.
