### ISSUE TITLE
ormconfig with multiple connection [Blocking issue]

### ISSUE THREAD

**Issue by kKen94** [w3tecch/typeorm-seeding#27]
Hi.

If ormconfig is set for multiple-environment seeds throw error, while application starts normally

![image](https://user-images.githubusercontent.com/46461611/69917917-b9d4ab00-146b-11ea-819c-40de99111098.png)

![image](https://user-images.githubusercontent.com/46461611/69917920-cf49d500-146b-11ea-850e-61a0ac4d78ea.png)

**Comment by betiol** [comment]
Same problem here :/
@kKen94 you already solved this issue?

**Comment by kKen94** [comment]
Nope, and no one answers me 🤔

**Comment by betiol** [comment]
bro, I've just added this lines to support multiple connections and I'm using this in my projects;
[see here](https://github.com/betiol/typeorm-seeding/blob/293eec2136ad24690c5ae00fca2d4b45364ab8f6/src/commands/seed.command.ts#L42)

You can use.
```"typeorm-seeding": "betiol/typeorm-seeding"```

**Comment by kKen94** [comment]
Cool!! Can you make a pull request to original repo?

**Comment by hirsch88** [comment]
hi @kKen94 
I have finally included this feature. check out the new version 1.4.0
