### ISSUE TITLE
Improve error output

### ISSUE THREAD

**Issue by RobinRadic** [w3tecch/typeorm-seeding#3]
Errors that occur during seeding are catched. Then a new error is thrown which does not include the original error message/name. 

EntityFactory:
```js
try {
  const entity = yield this.make();
  return yield em.save(entity);
}
catch (error) {
  throw new Error('Could not save entity');
}
```

**Comment by hirsch88** [comment]
Hi @RobinRadic I improved the error handling and released a new version 1.0.0-rc.1.
Thanks for reporting
