### ISSUE TITLE
Does not work with `export default`

### ISSUE THREAD

**Issue by stephanoparaskeva** [w3tecch/typeorm-seeding#39]
I have a config file called ```dev_seed.ts``` and inside it:
```JavaScript
export default {
  ...
  seeds: ['db/seed/**/*.seed.ts'],
  factories: ['db/factory/**/*.factory.ts'],
};
```

This does not work when running command:
```    "seed": "ts-node-dev ./node_modules/typeorm-seeding/dist/cli.js seed --config /db/seed/config/dev_seed.ts" ```

Where as this code with same command does work:
```JavaScript
module.exports = {
  ...
  seeds: ['db/seed/**/*.seed.ts'],
  factories: ['db/factory/**/*.factory.ts'],
};
```

**Comment by hirsch88** [comment]
Hi @stephanoparaskeva 
TypeORM looks for a .js or json file not a TypeScript one.
