### ISSUE TITLE
Entity with @Column('simple-array') fails to seed

### ISSUE THREAD

**Issue by benbender** [w3tecch/typeorm-seeding#4]
Some column-types in typeorm are resolving to objects. For example entitites with column-type "simple-array" failing to seed because the following expression is "true":

https://github.com/w3tecch/typeorm-seeding/blob/9e9c59118a5a4bbc171d3c4eb79e0f15523976ac/src/entity-factory.ts#L90

and the subentity can't be resolved. These issue is even harder to grasp, because the thrown error says simply "Error: Could not save entity".

**Comment by ashelkov** [comment]
the same issue with @column({ type: ''json })
