### ISSUE TITLE
Is there a way to Undo or Revert seeding?

### ISSUE THREAD

**Issue by stephanoparaskeva** [w3tecch/typeorm-seeding#40]
Is it possible to remove the seeded data via a command? and if not, how would one achieve this reliably?

**Comment by hirsch88** [comment]
Hi @stephanoparaskeva 
I use this command to clean the database.
```
    "schema:drop": "ts-node ./node_modules/typeorm/cli.js schema:drop",
```
just add this to the scripts in your package.json.
