### ISSUE TITLE
Usage for unit testing

### ISSUE THREAD

**Issue by mcousillas6** [w3tecch/typeorm-seeding#41]
First of all, thanks for the awesome lib!

I was wondering if there's some way of using the factories to seed specific data for unit testing.

**Comment by eugenio165** [comment]
By specific data do you mean data you can pass in to the factory?

Because you can pass in a `settings` object which you yourself can define to receive in the factory.
```
import { Tag } from '../../tags/tags.entity';
import * as Faker from 'faker';
import { define } from 'typeorm-seeding';

define(Tag, (faker: typeof Faker, settings: { name: string }) => {

    const tag = new Tag();
    if (!!settings) {
        tag.name = settings.name;
    } else {
        tag.name = faker.name.firstName();
    }

    return tag;
});
```

and then, customize the tag name using
`let tag = await factory(Tag)({ name: 'delicious' }).seed();`

**Comment by hirsch88** [comment]
Hi @mcousillas6  & @eugenio165 

Check out the seeding data in testing.
https://github.com/w3tecch/typeorm-seeding#-seeding-data-in-testing

**Comment by btilford** [comment]
Is it possible to use the factories without any database connection or calling `useSeeding()`?

**Comment by iwt-gabrielaoskroba** [comment]
@hirsch88 @jorgebodega I also wonder, is that possible to not use database connection to test `*.seed.ts` or `*.factory.ts` files?
Like those (from example project) https://github.com/copa-ch/copa-backend/tree/master/src/database
