### ISSUE TITLE
README has wrong .env configs

### ISSUE THREAD

**Issue by camezcua12** [w3tecch/typeorm-seeding#44]
Just started using the package on a personal project, and couldn't make the seeds run. I was getting some "Cannot read property 'name' of undefined", so I jumped into the source code, to try and find the error. It comes from what the README states about settings the ".env" configs:

> or add the following variables to your .env file.
`TYPEORM_SEEDING_FACTORIES=src/seeds/**/*{.ts,.js}
TYPEORM_SEEDING_SEEDS=src/factories/**/*{.ts,.js}`

As you might noticed, the paths are inverted to the actual feature it should belong to, so `src/seeds` is used for Factories, and `src/factories` is used for Seeds.

**Comment by hirsch88** [comment]
Hi @camezcua12 
Thanks for the creating the issue.
Have fixed it.
