### ISSUE TITLE
Pass open connection?

### ISSUE THREAD

**Issue by IanPirro** [w3tecch/typeorm-seeding#57]
Hey there, 

Looking to see if there is a was to use an existing connection. While using in tests in a nestjs app I have a case like this ->

```
beforeAll(async () => {
    const module = await Test.createTestingModule({
      imports: [
        ConfigModule.forRoot({ isGlobal: true }),
        MyTestModule,
        TypeOrmModule.forRoot({
          type: 'postgres',
          host: process.env.TYPEORM_HOST,
          port: Number(process.env.TYPEORM_PORT),
          username: process.env.TYPEORM_USERNAME,
          password: process.env.TYPEORM_PASSWORD,
          database: process.env.TYPEORM_DATABASE,
          logging: false,
          entities: ['src/**/*.entity{.ts,.js}'],
          synchronize: false,
        }),
      ],
    }).compile()
    app = module.createNestApplication()
    await app.init()

    // Is it possible to use the connection 'default' created by the test application
    await useRefreshDatabase()
  })
```

Basically looking to avoid `AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.`

Is there a way to use an existing connection, or do I just need to make a new one for typeorm-seeding? If so where would I specify a name for that.

**Comment by abettke** [comment]
It would be nice to be able to pass connection options directly to this library to override any values that may be set in the `ormconfig.json` or in the event this file doesn't exist. 

`await useSeeding({ ...connectionOptions })` <--- passing ConnectionOptions directly

**Comment by hirsch88** [comment]
Hi @IanPirro  & @abettke 

1. with `setConnectionOptions` you can override the configs.
2. now `useRefreshDatabase`uses already existing connection.

Example

```typescript
  let connection: Connection
  beforeAll(async (done) => {
    setConnectionOptions({
      type: 'sqlite',
      database: ':memory:',
      entities: ['sample/entities/**/*{.ts,.js}'],
    })
    connection = await useRefreshDatabase()
    await useSeeding()
    done()
  })
```

Are these changes helpful for you guys?

**Comment by IanPirro** [comment]
@hirsch88 Thanks for the quick reply, PR looks good this is what I did on a local fork in createConnection to get this to work, the connection options override is nice as well.

**Comment by abramyk-mv** [comment]
Hi @hirsch88,

Does your solution still require the presence of `ormconfig` file, right?
