### ISSUE TITLE
Feat: Support async ormconfig (Feature request) 

### ISSUE THREAD

**Issue by jaynish-zen** [w3tecch/typeorm-seeding#60]
Typeform currently supports async ormconfig. It would be good to have it in this library.

You can check it here:
https://github.com/typeorm/typeorm/pull/5048

**Comment by wwasowicz** [comment]
That works or me

typeorm.ts
```
export = (async () => {
    return  {
      type: '',
      schema: ''
    };
})();
```
package.json
`"seed": "ts-node -r tsconfig-paths/register ./node_modules/typeorm-seeding/dist/cli.js -n ormconfig.ts",`
