### ISSUE TITLE
[Bug] Root Param should be respected in OrmConfig file

### ISSUE THREAD

**Issue by johannesschobel** [w3tecch/typeorm-seeding#63]
Dear @hirsch88 ,

today i tried to add your library to my existing project in order to provide respective seeding functionality.

For the context, please note that i use a mono-repository with `nrwl/nx`. I have a few applications (all stored in `apps/` folder of my project root), whereas one is a `NestJS API`. The latter uses `TypeORM` with an `ormconfig.js` file and your library.

However, when i want to run the commands, i have to set the additional `--root` parameter, because my `ormconfig.js` file is not stored in the `root` folder of the mono-repository, but in the specific application folder (e.g., `apps/api/src/ormconfig.js`).

My `apps/api/src/ormconfig.js` file looks like this:
```js
module.exports = {
  // ... lots of params to connect to the database
  synchronize: false,
  seeds: ['my/custom/path/to/seeds/*.ts'],
};
```

However, because i need to call the seeder command with `--root` param, i expected the `seeds` parameter to prepend respective `root` path. For example, the path should be `apps/api/src/my/custom/path/to/seeds/*.ts`.

Not sure, if i did something wrong, but my seeds were not properly found. If i entered the full path (relative to the root folder of the project itself) it worked out!

All the best

**Comment by hirsch88** [comment]
Hi @johannesschobel unfortunately you have to use the `--root` argument for monorepos. Howerver, if you run the seed command inside of your `apps/api` folder it should work.

**Comment by aledoroshenko** [comment]
And what is the correct way to set `root`? Having `projectName/src/config/typeorm.config.ts` I'm trying this: `"seed:config": "ts-node ./node_modules/typeorm-seeding/dist/cli.js config --configName typeorm.config.ts --root /src/config"`, but have an error `Error: Cannot find module '/src/config/typeorm.config.ts'`.

**Comment by SaveYourTime** [comment]
> And what is the correct way to set `root`? Having `projectName/src/config/typeorm.config.ts` I'm trying this: `"seed:config": "ts-node ./node_modules/typeorm-seeding/dist/cli.js config --configName typeorm.config.ts --root /src/config"`, but have an error `Error: Cannot find module '/src/config/typeorm.config.ts'`.

Same here!

**Comment by trompx** [comment]
Same here, the doc is not in sync with how it works currently.
What worked for me is to specify the whole config path with configName, omitting root completly:
`--configName ./src/api/config/ormconfig.js`
