### ISSUE TITLE
Seeder Ordering?

### ISSUE THREAD

**Issue by DanjBethel** [w3tecch/typeorm-seeding#64]
How do I control the order in which the seeds are ran, for example when it comes to seeding entities with relations, I assume one seed would have to be ran before the other?

**Comment by hirsch88** [comment]
Hi @DanjBethel there is no ordering the seeds implemented. The idea was that the seeds should be isolated and run one use case like `createAdminUserWithPets.seed.ts`. With that we do not need any ordering.
