### ISSUE TITLE
Generation structure of seeding files

### ISSUE THREAD

**Issue by capinemo** [w3tecch/typeorm-seeding#66]
Hello!
Typeorm has command for generation migration files: `typeorm migration:generate`. Is planned the same feature in typeorm-seeding? This feature will by useful in cases when we want to fill database some data such as catalogues, lists etc.

**Comment by hirsch88** [comment]
Hi @capinemo 
This is not planned yet. However, feel free to create a pull-request with it. I would be very happy to integrated it with you.

**Comment by capinemo** [comment]
Thank you for answer!
Then i will implement this functionality.

**Comment by nathanagez** [comment]
@capinemo do you need any help ? Feel free to ask !

**Comment by capinemo** [comment]
@nathanagez thanks!
There shouldn't be any problems yet. If i have any questions, i will ask them.

**Comment by hirsch88** [comment]
Hi @nathanagez 
What is the state of your implementation?

**Comment by capinemo** [comment]
Hi! Sorry, work, family...
File generation is solved:
https://github.com/w3tecch/typeorm-seeding/compare/master...capinemo:seed_generate
But it has problem. I thought that running this files must work as typeorm - data seeded and file name saved handled file into 'migrations' table to db. If we use typeorm's table (migrations) we must use it methods, but it is protected. If we decide to realize similar logic, we will double this logic((
