### ISSUE TITLE
EntityFactory using .map give me an error

### ISSUE THREAD

**Issue by gerzok** [w3tecch/typeorm-seeding#69]
I ran the example (User and Pet) that you have here and I am getting this error:

`(property) User.pets: Pet[]
This expression is not callable.
  Type 'Pet[]' has no call signatures.`

I used this as seeder:

`await factory(User)()
  .map(async (user: User) => {
    const pets: Pet[] = await factory(Pet)().createMany(2)
    const petIds = pets.map((pet: Pet) => pet.Id)
    await user.pets().attach(petIds)
  })
  .createMany(5)`

Any idea?

**Comment by SaveYourTime** [comment]
I look up the source code, nothing is related to the `attach` method.
Finally, I use the following way to achieve that

**_/src/database/seeds/create-users.seeds.ts_**
```javascript
import { Factory, Seeder } from 'typeorm-seeding';
import { Auth } from '../../auth/auth.entity';
import { User } from '../../users/user.entity';
import { Task } from '../../tasks/task.entity';

export default class CreateUsers implements Seeder {
  public async run(factory: Factory): Promise<any> {
    const users = await factory(User)().createMany(10);

    for (const user of users) {
      const { id } = user;

      await factory(Auth)({ id }).create();
      await factory(Task)({ id }).create();
    }
  }
}

```

**Comment by trompx** [comment]
Same problem here, I have foreignKeys between tables thus I first seed one entity, get all generated ids and pass them to the other entity (this is not ideal).
``` ts
const tasks = await factory(Tasks)().createMany(10)
const myIds = tasks.map(a => a.id)
await factory(User)({
  myIds
}).createMany(2)
```

I tried your solution @SaveYourTime but it didn't work, when seeding, my arrayIds I pass are undefined.
I'm not using faker but chance, so I declare it this way:
``` ts
import { define } from 'typeorm-seeding';
import { User } from '../../user/user.entity';
import { Chance } from 'chance';

interface Context {
  myIds: Array<number>;
}

define(User, (context: Context) => {
    const chance = new Chance();
    const { myIds } = context; // -> undefined
    ...
}
```
That would be great if typeorm-seeding could let us pick one already existing entry directly in the factory instead of having to pass the ids manually.

**Comment by SaveYourTime** [comment]
> Same problem here, I have foreignKeys between tables thus I first seed one entity, get all generated ids and pass them to the other entity (this is not ideal).
> 
> ```ts
> const tasks = await factory(Tasks)().createMany(10)
> const myIds = tasks.map(a => a.id)
> await factory(User)({
>   myIds
> }).createMany(2)
> ```
> 
> I tried your solution @SaveYourTime but it didn't work, when seeding, my arrayIds I pass are undefined.
> I'm not using faker but chance, so I declare it this way:
> 
> ```ts
> import { define } from 'typeorm-seeding';
> import { User } from '../../user/user.entity';
> import { Chance } from 'chance';
> 
> interface Context {
>   myIds: Array<number>;
> }
> 
> define(User, (context: Context) => {
>     const chance = new Chance();
>     const { myIds } = context; // -> undefined
>     ...
> }
> ```
> 
> That would be great if typeorm-seeding could let us pick one already existing entry directly in the factory instead of having to pass the ids manually.

You got undefined cause you’re destructuring the faker object, you can not omit the first argument `(thisArgumentStillNeedsToExist, context: Context)`

**Comment by trompx** [comment]
I get this error when I use `(faker: any, context: Context)`.
``` ts
Argument of type '(faker: any, context: Context) => User' is not assignable to parameter of type 'FactoryFunction<User, Context>'.
  Types of parameters 'context' and 'context' are incompatible.
    Type 'Context | undefined' is not assignable to type 'Context'.
      Type 'undefined' is not assignable to type 'Context'.ts(2345)
```

If I use `(faker: any, context: undefined)` I get: ` 'faker' is declared but its value is never read.`
If I use `(fcontext: undefined)` no error but I can't get myIds from the context in the define function.

**Comment by trompx** [comment]
Instead of passing the ids to the factory, I manage to directly use them in the seeder to override specific fields:
```
    await factory(Product)().createMany(10, {
      category: chance.pickone(categoryIds),
      brand: chance.pickone(brandIds)
    })
```
It works **only by passing them in the createMany parameters** , not in (Product)().
I would still prefer being able to declare an existing id directly inside the factory rather than passing them like that.

**Comment by vegtelenseg** [comment]
> define(User, (context: Context) => {
>     const chance = new Chance();
>     const { myIds } = context; // -> undefined
>     ...
> }
> ```

`context` is the second argument of that callback, not first

**Comment by vegtelenseg** [comment]
> Instead of passing the ids to the factory, I manage to directly use them in the seeder to override specific fields:
> 
> ```
>     await factory(Product)().createMany(10, {
>       category: chance.pickone(categoryIds),
>       brand: chance.pickone(brandIds)
>     })
> ```
> 
> It works **only by passing them in the createMany parameters** , not in (Product)().
> I would still prefer being able to declare an existing id directly inside the factory rather than passing them like that.
> 
> Edit: finally this is not working as expected, chance.pickone is not random for each product created, it only executes once so set the same value for all products.

That is the intended behavior.
This is the implementation of `createMany`

```
  public async createMany(amount: number, overrideParams: EntityProperty<Entity> = {}): Promise<Entity[]> {
    const list = []
    for (let index = 0; index < amount; index++) {
      list[index] = await this.create(overrideParams)
    }
    return list
  }
```

As you can see, it simply loops as many times as specified by `amount` calling create with the same data you passed.

**Comment by AmrAbdalrahman** [comment]
> I look up the source code, nothing is related to the `attach` method.
> Finally, I use the following way to achieve that
> 
> #### seeds
> **_/src/database/seeds/create-users.seeds.ts_**
> 
> ```js
> import { Factory, Seeder } from 'typeorm-seeding';
> import { User } from '../../users/user.entity';
> import { Task } from '../../tasks/task.entity';
> 
> export default class CreateUsers implements Seeder {
>   public async run(factory: Factory): Promise<any> {
>     const users = await factory(User)().createMany(10);
> 
>     for (const user of users) {
>       const { id } = user;
> 
>       await factory(Task)({ id }).create();
>     }
>   }
> }
> ```
> 
> #### factory
> **_/src/database/factories/task.factory.ts_**
> 
> ```js
> import Faker from 'faker';
> import { define } from 'typeorm-seeding';
> import { Task } from '../../tasks/task.entity';
> import { TaskStatus } from '../../tasks/task-status.enum';
> 
> interface Context {
>   id: number;
> }
> 
> define(Task, (faker: typeof Faker, context: Context) => {
>   const { id } = context; // <--- here!
> 
>   const title = faker.lorem.words();
>   const description = faker.lorem.paragraph();
>   const status = faker.random.objectElement<TaskStatus>(TaskStatus);
> 
>   const task = new Task();
>   task.title = title;
>   task.description = description;
>   task.status = status;
>   task.userId = id; // <--- here!
>   return task;
> });
> ```

thanks, works well with me .
my once editing to solve the error was shown to me is making `(faker: typeof Faker, context: ViewInterface | any)`
