### ISSUE TITLE
Allow to override faker's attributes in the seed and make methods

### ISSUE THREAD

**Issue by clovis1122** [w3tecch/typeorm-seeding#7]
With Laravel factories, you can do this:

```php
$user = factory(App\User::class)->create([
    'type' => 'Admin',
]);
```

Which is great, because it allows to quickly create many entities with the specified attributes. Right now this is not possible in `typeorm-seeding` and you're forced into writing something like this:

```typescript
const bruce = await factory(User)().make();
const em = connection.createEntityManager();

bruce.name = 'Bruce Lee';
await em.save<Entity>(bruce);
```

Or for many users:

```typescript
const tenAdmins = await factory(User)().makeMany(10);
const em = connection.createEntityManager();
tenAdmins.forEach(user => user.type = 'Admin');
await Promise.all(tenAdmins.map(user => em.save<Entity>(user)));
```

Which feels awkward to do.

Using the `map()` method feels less awkward. For a single key you can get away inlining the function but for multiple keys overriding you'll need to make it too verbose or lose some type safety.

```typescript
const tenAdmins = await factory(User)()
  .map((user) => {
     user.type = 'Admin';
     user.name = 'John Doe';
     return user;
  })
  .seedMany(10);
```

I'm proposing that we make the methods `make` and `seed` (and as the second argument for `makeMany` and `seedMany`) that accepts an object that overrides the faker attributes.

**Comment by agustif** [comment]
I'm not sure about the actual implementation proposed, but I would love a way to seed my own json/yaml files which could be an big or multiple jsons or yaml files, and use it to import my old data to a freshh new postgresql/typeorm dtabase

+1 for that

**Comment by clovis1122** [comment]
@agustif, like this? https://github.com/RobinCK/typeorm-fixtures

**Comment by hirsch88** [comment]
Hi @clovis1122 I merged the feature and release a new version, which also include a cli.
