### ISSUE TITLE
If entity has @AfterInsert() - seeding for this entity will never finished

### ISSUE THREAD

**Issue by volovodenko** [w3tecch/typeorm-seeding#70]
Actualy the issue is in the title

**Comment by volovodenko** [comment]
@AfterInsert()
    async payForReview() {
        const transaction = new ReputationTokensTransaction();
        transaction.amount = -settings.action_price.review;
        transaction.reason = 'Review pay';
        transaction.entity = Promise.resolve(this);
        transaction.user = this.user;

        await getRepository(ReputationTokensTransaction).save(transaction);
    }

**Comment by hirsch88** [comment]
Hi @volovodenko 
Did you find any solution?

**Comment by volovodenko** [comment]
Actualy the issue was in getRepository(ReputationTokensTransaction). When we run seeding, app hasn't started yet, and getRepository isn't working. I decided to use @EventSubscriber() instead @AfterInsert()......I have different database config file (for app one and for migrating/seeding another one), in config file for migrating/seeding I have excluded property "subscribers " and that's all.
