### ISSUE TITLE
TypeError: clazz is not a constructor

### ISSUE THREAD

**Issue by volovodenko** [w3tecch/typeorm-seeding#71]
typescript 3.9.3 has thrown that exception
![image](https://user-images.githubusercontent.com/29176940/82675148-0fd12100-9c4d-11ea-8b21-e98be4934f9d.png)

**Comment by Drakota** [comment]
Getting the same thing, have you found something?

**Comment by squareloop1** [comment]
Had the same issue a while ago. The issue was exporting other stuff from the seed file. It should work if you just have one default export of the seeder in the file.

Maybe this can be fixed to be able to export other variables (like mock data objects).

**Comment by hirsch88** [comment]
Could you please add your seed file?
Only with that I can reproduce the error.

**Comment by volovodenko** [comment]
I found out why it happens.
Seeder file had both constant and seeder class

`export default class CountriesSeeder implements Seeder {
    async run(factory: Factory, connection: Connection): Promise<any> {
        await connection.createQueryBuilder().insert().into(CountryEntity).values(countries).execute();
    }
}

interface Country {
    code: string;
    name: string;
}

const countries: Country[] = [
    { code: 'AD', name: 'Andorra' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'AF', name: 'Afghanistan' },
.........
];`

As far as i understood it's not allowed

**Comment by alirezaKhaki** [comment]
> Had the same issue a while ago. The issue was exporting other stuff from the seed file. It should work if you just have one default export of the seeder in the file.
> 
> Maybe this can be fixed to be able to export other variables (like mock data objects).

thanks, that will correct the issue!
