### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by tanlong14** [w3tecch/typeorm-seeding#72]
Hello,

I have a problem with initializing test data

I run this CLI: 
"seed:config": "ts-node ./node_modules/typeorm-seeding/dist/cli.js config"

and this
"seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js seed -n"

And I have this error message:
![image](https://user-images.githubusercontent.com/2587508/83054200-54482c80-a052-11ea-832b-d5a95487ae66.png)

Why ?

My package.json file:
`{
  "name": "xxxxxxxx",
  "version": "0.0.1",
  "description": "Graphql with TypeORM",
  "private": true,
  "license": "",
  "scripts": {
    "start": "ts-node src/graphql/server.ts",
    "migrate:create": "ts-node ./node_modules/typeorm/cli.js migrations:create",
    "migrate:generate": "ts-node ./node_modules/typeorm/cli.js migrations:generate",
    "migrate:run": "ts-node ./node_modules/typeorm/cli.js migration:run",
    "schema:drop": "ts-node ./node_modules/typeorm/cli.js schema:drop",
    "schema:sync": "ts-node ./node_modules/typeorm/cli.js schema:sync",
    "schema:log": "ts-node ./node_modules/typeorm/cli.js schema:log",
    "seed:config": "ts-node ./node_modules/typeorm-seeding/dist/cli.js config",
    "seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js seed -n",
    "db:setup": "npm run schema:drop && npm run schema:sync && npm run seed:config && npm run seed:run"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.2",
    "@types/express": "^4.17.6",
    "@types/express-session": "^1.17.0",
    "@types/faker": "^4.1.12",
    "@types/lodash": "^4.14.153",
    "@types/node": "^14.0.5",
    "prettier": "^2.0.5",
    "ts-node": "^8.10.1",
    "typescript": "^3.9.3"
  },
  "dependencies": {
    "@types/express": "^4.17.6",
    "apollo-server-express": "^2.14.0",
    "bcryptjs": "^2.4.3",
    "class-validator": "^0.12.2",
    "express": "^4.17.1",
    "express-session": "^1.17.1",
    "graphql": "^15.0.0",
    "lodash": "^4.17.15",
    "mysql": "^2.18.1",
    "reflect-metadata": "^0.1.13",
    "typeorm": "^0.2.25",
    "typeorm-seeding": "^1.6.1"
  }
}
`

My ormconfig.json file:
`[
  {
    "name": "default",
    "type": "mysql",
    "host": "localhost",
    "port": 3306,
    "username": "admin",
    "password": "admin",
    "database": "mydb",
    "synchronize": true,
    "logging": true,
    "logger": "file",
    "entityPrefix": "",
    "entities": ["src/db/entity/**/*.ts"],
    "migrations": ["src/db/migration/**/*.ts"],
    "subscribers": ["src/db/subscriber/**/*.ts"],
    "factories": ["src/db/factories/**/*.ts"],
    "seeds": ["src/db/seeds/**/*.ts"],
    "cli": {
      "entitiesDir": "src/db/entity",
      "migrationsDir": "src/db/migration",
      "subscribersDir": "src/db/subscriber",
      "factoriesDir": "src/db/factories",
      "seedsDir": "src/db/seeds"
    }
  }
]
`

My tsconfig.json file:
`{
   "compilerOptions": {
      "lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
      "target": "es5",
      "module": "commonjs",
      "sourceMap": true,
      "moduleResolution": "node",
      "outDir": "./build",
      "removeComments": true,
      "noImplicitAny": true,
      "strictNullChecks": true,
      "strictFunctionTypes": true,
      "noImplicitThis": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noImplicitReturns": true,
      "noFallthroughCasesInSwitch": true,
      "allowSyntheticDefaultImports": false,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true
   },
   "exclude": ["node_modules"],
   "include": ["./src/**/*.tsx", "./src/**/*.ts"]
}`

**Comment by tanlong14** [comment]
Hello, 
I find my problem. I'm stupid, I create a file "config.ts" in folder "seeds".

**Comment by ryuseongryong** [comment]
Hello, I have same problem OTL
What's meaning of "create a file 'config.ts' in folder 'seeds'"?
Does need config.ts file in this case?

**Comment by ryuseongryong** [comment]
oh, I solved
If empty Seed File is existed, does not work.

**Comment by rolandbobek** [comment]
I've spent like 2 hours to debug this.

Looks like, if you have an index.ts file in the seeds directory (or any other file which is not actually a seed) it does not work because it tries to run every file in the directory as a seed file.

A best best practice could be to suffix files with .seed.ts and narrow the glob pattern to `./src/database/seeds/**/*.seed.{ts, js}`
