### ISSUE TITLE
`context` is not inserted by default?

### ISSUE THREAD

**Issue by michaelwooley** [w3tecch/typeorm-seeding#76]
Hi, I'm trying to make some factories that make use of context.

Take a slightly modified version of the sample:

```ts
import * as Faker from 'faker'
import { define } from '../../src/typeorm-seeding'
import { User } from '../entities/User.entity'

// user.factory.ts

define(User, (faker: typeof Faker) => {
  const gender = faker.random.number(1)
  const firstName = faker.name.firstName(gender)
  const lastName = faker.name.lastName(gender)
  const email = faker.internet.email(firstName, lastName)

  const user = new User()
  user.firstName = firstName
  user.lastName = lastName
  user.middleName = null
  user.email = email
  user.password = faker.random.word()

  user.roles = ['basic']; /* <---- Explicitly declare default for roles */

  return user
});

// pet.factory.ts

define(Pet, (faker: typeof Faker) => {
  const gender = faker.random.number(1)
  const name = faker.name.firstName(gender)

  const pet = new Pet()
  pet.name = name
  pet.age = faker.random.number()

  pet.user = factory(User)({ roles: ['admin'] }) as any /* <---- Expect this to override ["basic"] */

  return pet
});
```

# Expected behavior

- Specified a "default" `user.roles = ["basic"]` in `user.factory.ts`
- If create user with passed context (e.g. `factory(User)({ roles: ['admin'] })`) then the created user will have `roles = ['admin']`
- Otherwise, default to the value specified in the module: `roles = ['basic']`

# Actual behavior

- In the above example, 

# Question/Suggestions

It looks like the correct way to do this would be:

```ts
define(User, (faker: typeof Faker, context: Record<string, any>) => {
  // ...
  user.roles = context.roles || ['basic']; /* <---- Explicitly declare default for roles */

  return user
});
```
Is that correct? (I've got mine working for this.) If so, it does kind of junk up the factory factory. 

Would it perhaps be possible to add on the context after the fact as [appears to be the case](https://github.com/w3tecch/typeorm-seeding/blob/master/src/entity-factory.ts#L98) with a call like `factory(User)().make({ roles: ['admin'] })`

Alternatively, is there any downside associated with something like this?

```ts
// user.factory.ts

// LEAVE AS-IS

// pet.factory.ts

define(Pet, (faker: typeof Faker) => {
  // ....
  pet.user = factory(User)().make({ roles: ['admin'] }) as any /* <---- Expect this to override ["basic"] */

  return pet
});
```

This also seems to work. Looking [here](https://github.com/w3tecch/typeorm-seeding/blob/master/src/entity-factory.ts#L113), returning a promise does seem to be kosher.

If so, would it make sense to change the signature of `FactoryFunction` to:

```ts
export type FactoryFunction<Entity, Context> = (faker: typeof Faker, context?: Context) => Entity | Promise<Entity>
```

so that you could make this fact a bit more explicit? For example:

```ts
define(Pet, async (faker: typeof Faker) => {
  // ....
  pet.user = await factory(User)().make({ roles: ['admin'] }) as any /* <---- Expect this to override ["basic"] */

  return pet
});
```

I guess the downside of this suggestion is that you want to help people to avoid calling `create` before the parent has been validated/created? Perhaps there are also potential circular dependency issues?

**Comment by hirsch88** [comment]
Hi @michaelwooley 
Thanks for the good describe issue.
The idea of the context is to pass any kind of a parameter into the factory. 
For example to add a type like 'superman'.
```
define(User, (faker: typeof Faker, context: { type: string }) => { 
    if(type === 'superman') {
        firstname = 'clark'
    }
    ...
 })
```
