### ISSUE TITLE
[BUG] CLI Options --root doesn't work as expect

### ISSUE THREAD

**Issue by SaveYourTime** [w3tecch/typeorm-seeding#78]
According to the doc [cli-options](https://github.com/w3tecch/typeorm-seeding#cli-options) shows that if your `ormconfig.js` is not located at the root of your project, you can use `--root (or -r)` to tell cli where's the path to the typeorm config file.

Say you have a ormconfig.js file located at `src/config`, and the folder structure would be this...
- /src
  - /config
    - ormconfig.js

Then, you should add the option `-r src/config` to your script...
```
"seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js seed -r src/config"
```
> I tried `src/config`, `/src/config`, `./src/config`

After running this script, I got an error like this...

<img width="800" alt="截圖 2020-07-02 上午10 24 24" src="https://user-images.githubusercontent.com/35715664/86309409-3e7be780-bc4e-11ea-8902-5fc4b0920190.png">

Therefore, the options of `--root (or -r)` don't seems to work!

---

I found that some of the users may run into the same error. #63 #75 

The temporary fix to the problem is to use `--name (or -n)` instead of `--root (or -r)`.
```
"seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js seed -n src/config/ormconfig.js"
```

> Thanks to @achmadfatoni: https://github.com/w3tecch/typeorm-seeding/issues/75#issuecomment-652211140

**Comment by nathandaly** [comment]
@SaveYourTime Thanks, this helped me as indeed the `--root` is not working correctly.

`"seed:run": "ts-node ./node_modules/typeorm-seeding/dist/cli.js seed --root libs/configuration/src/config --configName=ormcliconfig.ts",`

```
├── libs
│   ├── configuration
│   │   ├── src
│   │   │   ├── config
│   │   │   │   ├── configuration.ts
│   │   │   │   ├── ormcliconfig.ts
│   │   │   │   ├── ormconfig.ts
│   │   │   │   ├── redisconfig.ts
│   │   │   │   └── validation.ts
```

![error image](https://i.imgur.com/SMJh4gS.png)
