### ISSUE TITLE
Error: Cannot find module (typeorm entity)

### ISSUE THREAD

**Issue by xcymax** [w3tecch/typeorm-seeding#81]
When I do `seed:run` in my NestJS app I get the following error:
```
�  TypeORM Seeding v1.6.1
- Loading ormconfig
✔ ORM Config loaded
- Import Factories
✖ Could not import factories!
Error: Cannot find module 'src/users/user.entity'
Require stack:
- C:\Users\User\Development\example\example-api\src\database\factories\user.factory.ts
- C:\Users\User\Development\example\example-api\node_modules\typeorm-seeding\dist\utils\file.util.js
- C:\Users\User\Development\example\example-api\node_modules\typeorm-seeding\dist\commands\seed.command.js
- C:\Users\User\Development\example\example-api\node_modules\typeorm-seeding\dist\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\User\Development\example\example-api\src\database\factories\user.factory.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (C:\Users\User\Development\example\example-api\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\User\Development\example\example-api\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\Development\\example\\example-api\\src\\database\\factories\\user.factory.ts',
    'C:\\Users\\User\\Development\\example\\example-api\\node_modules\\typeorm-seeding\\dist\\utils\\file.util.js',
    'C:\\Users\\User\\Development\\example\\example-api\\node_modules\\typeorm-seeding\\dist\\commands\\seed.command.js',
    'C:\\Users\\User\\Development\\example\\example-api\\node_modules\\typeorm-seeding\\dist\\cli.js'
  ]
}
```

This is my `seed:config`:
```
�  TypeORM Seeding v1.6.1
{
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'example',
  password: 'example',
  database: 'example',
  entities: [ 'dist/**/*.entity{.ts,.js}' ],
  migrations: [ 'migration/*.js' ],
  cli: { migrationsDir: 'migration' },
  synchronize: true,
  factories: [ 'src/database/factories/**/*{.ts,.js}' ],
  seeds: [ 'src/database/seeds/**/*{.ts,.js}' ]
}
```

TypeORM is working fine with my app, but not this seeding package.

**Comment by eugenio165** [comment]
Hi xcymax, i've had this problem in the past. This happens because you're using absolute paths. You should use relative paths in all your imports, so that when you run your code in prod mode, which would normally be something like `node dist/main` it all works correctly. 

Also, in my experience i could not get my typeorm configuration to work with both `.ts` and `.js` files. If the above solution doesn't work, i recommend you use your configuration with only `.js` files and use nest cli's start command to start your project. This way, nest builds and executes your application straight with javascript, using the dist folder.

**Comment by xcymax** [comment]
Thank you @eugenio165 ! Changing all my imports to relative paths fixed that but I am now seeing a new error which I believe you were alluding to:
```
�  TypeORM Seeding v1.6.1
- Loading ormconfig
✔ ORM Config loaded
- Import Factories
✔ Factories are imported
- Importing Seeders
✔ Seeders are imported
- Connecting to the database
✔ Database connected
- Executing CreateUsers Seeder
❌  Could not save entity
EntityMetadataNotFound: No metadata for "User" was found.
    at new EntityMetadataNotFoundError (C:\Users\User\Development\example\example-api\src\error\EntityMetadataNotFoundError.ts:9:9)
    at Connection.getMetadata (C:\Users\User\Development\example\example-api\src\connection\Connection.ts:333:19)
    at C:\Users\User\Development\example\example-api\src\persistence\EntityPersistExecutor.ts:77:55
    at Array.forEach (<anonymous>)
    at EntityPersistExecutor.<anonymous> (C:\Users\User\Development\example\example-api\src\persistence\EntityPersistExecutor.ts:71:30)
    at step (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
    at C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:111:16) {
  name: 'EntityMetadataNotFound',
  message: 'No metadata for "User" was found.'
}
✖ Could not run the seed CreateUsers!
Error: Could not save entity
    at EntityFactory.<anonymous> (C:\Users\User\Development\example\example-api\node_modules\typeorm-seeding\src\entity-factory.ts:52:15)
    at step (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:140:27)
    at Object.throw (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:121:57)
    at rejected (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:112:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I tried running with `entities: [ 'dist/**/*.entity.js' ],` in my configuration and nest cli as you mentioned but am still seeing the same error.

Just getting into Nest/TypeORM so baby steps :).

**Comment by rbutera** [comment]
> Thank you @eugenio165 ! Changing all my imports to relative paths fixed that but I am now seeing a new error which I believe you were alluding to:
> 
> ```
> �  TypeORM Seeding v1.6.1
> - Loading ormconfig
> ✔ ORM Config loaded
> - Import Factories
> ✔ Factories are imported
> - Importing Seeders
> ✔ Seeders are imported
> - Connecting to the database
> ✔ Database connected
> - Executing CreateUsers Seeder
> ❌  Could not save entity
> EntityMetadataNotFound: No metadata for "User" was found.
>     at new EntityMetadataNotFoundError (C:\Users\User\Development\example\example-api\src\error\EntityMetadataNotFoundError.ts:9:9)
>     at Connection.getMetadata (C:\Users\User\Development\example\example-api\src\connection\Connection.ts:333:19)
>     at C:\Users\User\Development\example\example-api\src\persistence\EntityPersistExecutor.ts:77:55
>     at Array.forEach (<anonymous>)
>     at EntityPersistExecutor.<anonymous> (C:\Users\User\Development\example\example-api\src\persistence\EntityPersistExecutor.ts:71:30)
>     at step (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
>     at Object.next (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
>     at C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
>     at new Promise (<anonymous>)
>     at Object.__awaiter (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:111:16) {
>   name: 'EntityMetadataNotFound',
>   message: 'No metadata for "User" was found.'
> }
> ✖ Could not run the seed CreateUsers!
> Error: Could not save entity
>     at EntityFactory.<anonymous> (C:\Users\User\Development\example\example-api\node_modules\typeorm-seeding\src\entity-factory.ts:52:15)
>     at step (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:140:27)
>     at Object.throw (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:121:57)
>     at rejected (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:112:69)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> ```
> 
> I tried running with `entities: [ 'dist/**/*.entity.js' ],` in my configuration and nest cli as you mentioned but am still seeing the same error.
> 
> Just getting into Nest/TypeORM so baby steps :).

were you able to resolve this issue? trying to set up Nest / TypeORM integration tests and it seems like this topic is mostly unsupported in the nest ecosystem

**Comment by eugenio165** [comment]
@xcymax 
Make sure your using nest cli to run your project, have all the configurations, even `typeorm-seeding` configs routed to the files in the dist folder and make sure your entity files are correct. If that doesnt work, send a few lines worth of code from your entity file, your factory, your seed and your config so we can see whats going on.

**Comment by xcymax** [comment]
@eugenio165 
I have created a simple sample repo here: https://github.com/xcymax/nestjs-typeorm-seeding-sample - appreciate any help.

**Comment by eugenio165** [comment]
@xcymax 
The only thing i had to do was change the configs to route to the `.js` files in the dist folder, like i said earlier...
Good Luck!

```json
{
  "type": "postgres",
  "host": "localhost",
  "port": 5432,
  "username": "docker",
  "password": "docker",
  "database": "postgres",
  "entities": ["dist/**/*.entity.js"],
  "migrations": ["migration/*.js"],
  "cli": {
    "migrationsDir": "migration"
  },
  "synchronize": true,
  "factories": [ "dist/**/database/factories/**/*.js" ],
  "seeds": [ "dist/**/database/seeds/**/*.js" ]
}
```

**Comment by xcymax** [comment]
Oh now I understand, I was only focused on the `entities` setting in the config. It works now when `factories` and `seeds` are also pointing to the `dist` location and `.js` only.

For clarification:
```
  "factories": ["dist/**/database/factories/**/*.js"],
  "seeds": ["dist/**/database/seeds/**/*.js"],
```

Thanks for the help!

**Comment by ponahoum** [comment]
Would recommand to install `tsconfig-paths` and in the seeding commands add ` -r tsconfig-paths/register`, ie:
<code>
    "fixtures:run:seed": "ts-node -r tsconfig-paths/register ./node_modules/typeorm-seeding/dist/cli.js seed -n src/fixtures/ormFixturesConfig.ts",
</code>

It solved my issue

**Comment by m3h0w** [comment]
> Hi xcymax, i've had this problem in the past. This happens because you're using absolute paths. You should use relative paths in all your imports, so that when you run your code in prod mode, which would normally be something like `node dist/main` it all works correctly.

That sounds like people who use absolute imports have never ran their code in production.

Is there any way to make typeorm-seeding work with absolute paths?

**Comment by svJariwala** [comment]
hello guys

When I do seed:run in my NestJS app I get the following error:

![image](https://user-images.githubusercontent.com/103307358/172137214-b3dfccd0-ab4f-4fb8-8ef3-738548865101.png)

This is my seed:config:

![image](https://user-images.githubusercontent.com/103307358/172137399-b03f0bfa-0c18-45af-8b65-2f231195231e.png)


This is my database.config.ts file

![image](https://user-images.githubusercontent.com/103307358/172138426-0d7d7267-5225-4d22-bc8f-25bd38d40351.png)

**Comment by Lobaton2020** [comment]
> > Thank you @eugenio165 ! Changing all my imports to relative paths fixed that but I am now seeing a new error which I believe you were alluding to:
> > ```
> > �  TypeORM Seeding v1.6.1
> > - Loading ormconfig
> > ✔ ORM Config loaded
> > - Import Factories
> > ✔ Factories are imported
> > - Importing Seeders
> > ✔ Seeders are imported
> > - Connecting to the database
> > ✔ Database connected
> > - Executing CreateUsers Seeder
> > ❌  Could not save entity
> > EntityMetadataNotFound: No metadata for "User" was found.
> >     at new EntityMetadataNotFoundError (C:\Users\User\Development\example\example-api\src\error\EntityMetadataNotFoundError.ts:9:9)
> >     at Connection.getMetadata (C:\Users\User\Development\example\example-api\src\connection\Connection.ts:333:19)
> >     at C:\Users\User\Development\example\example-api\src\persistence\EntityPersistExecutor.ts:77:55
> >     at Array.forEach (<anonymous>)
> >     at EntityPersistExecutor.<anonymous> (C:\Users\User\Development\example\example-api\src\persistence\EntityPersistExecutor.ts:71:30)
> >     at step (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:141:27)
> >     at Object.next (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:122:57)
> >     at C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:115:75
> >     at new Promise (<anonymous>)
> >     at Object.__awaiter (C:\Users\User\Development\example\example-api\node_modules\typeorm\node_modules\tslib\tslib.js:111:16) {
> >   name: 'EntityMetadataNotFound',
> >   message: 'No metadata for "User" was found.'
> > }
> > ✖ Could not run the seed CreateUsers!
> > Error: Could not save entity
> >     at EntityFactory.<anonymous> (C:\Users\User\Development\example\example-api\node_modules\typeorm-seeding\src\entity-factory.ts:52:15)
> >     at step (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:140:27)
> >     at Object.throw (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:121:57)
> >     at rejected (C:\Users\User\Development\example\example-api\node_modules\tslib\tslib.js:112:69)
> >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried running with `entities: [ 'dist/**/*.entity.js' ],` in my configuration and nest cli as you mentioned but am still seeing the same error.
> > Just getting into Nest/TypeORM so baby steps :).
> 
> were you able to resolve this issue? trying to set up Nest / TypeORM integration tests and it seems like this topic is mostly unsupported in the nest ecosystem

Many thanks, it works for me

**Comment by Lobaton2020** [comment]
> @xcymax The only thing i had to do was change the configs to route to the `.js` files in the dist folder, like i said earlier... Good Luck!
> 
> ```json
> {
>   "type": "postgres",
>   "host": "localhost",
>   "port": 5432,
>   "username": "docker",
>   "password": "docker",
>   "database": "postgres",
>   "entities": ["dist/**/*.entity.js"],
>   "migrations": ["dist/**/migration/*.js"],
>   "cli": {
>     "migrationsDir": "migration"
>   },
>   "synchronize": true,
>   "factories": [ "dist/**/database/factories/**/*.js" ],
>   "seeds": [ "dist/**/database/seeds/**/*.js" ]
> }
> ```

Appreciate your help, works for me
