### ISSUE TITLE
Is there any way to force an order in typeorm-seeding ??

### ISSUE THREAD

**Issue by joseSignot** [w3tecch/typeorm-seeding#91]
How to control which seed to run first

**Comment by Superoryco** [comment]
For me, just add a number on the seeders file name, e.g. 1-create-default-users.seed.ts | 2-creete-posts.seed.ts

**Comment by joseSignot** [comment]
That's my current solution Actually!

**Comment by joseSignot** [comment]
Should this be in the docs somewhere?
